var Name = "Maryum";
var age = 15;
var vowel = "a";
console.log("Is Name == 'Maryum'? I predict True.");
console.log(Name == 'Maryum');
console.log("Is Name == 'Abrar'? I predict False.");
console.log(Name == 'Abrar');
console.log("Is age < 18? I predict True.");
console.log(age < 18);
console.log("Is age > 13? I predict True.");
console.log(age > 13);
console.log("Is vowel != 'z'? I predict True.");
console.log(vowel != 'z');
